//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCards.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int IdAnswer { get; set; }
        public Nullable<int> IdPoint { get; set; }
        public Nullable<int> IdAuthorizations { get; set; }
        public Nullable<int> IdControlCard { get; set; }
        public string Title { get; set; }
    
        public virtual Authorizations Authorizations { get; set; }
        public virtual ControlCard ControlCard { get; set; }
        public virtual Points Points { get; set; }
    }
}
