//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCards.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlCard()
        {
            this.Answer = new HashSet<Answer>();
        }
    
        public int IdControlCard { get; set; }
        public Nullable<int> IdPattern { get; set; }
        public string SerialNumber { get; set; }
        public string FactoryNumber { get; set; }
        public Nullable<System.DateTime> DateOfAcceptance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual Pattern Pattern { get; set; }
    }
}
