//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlCards.Classes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlCardMalchikEntities : DbContext
    {
        public ControlCardMalchikEntities()
                    : base("name=ControlCardMalchikEntities")
        {
        }
        private static ControlCardMalchikEntities _context;

        public static ControlCardMalchikEntities GetContext()
        {
            if (_context == null)
                _context = new ControlCardMalchikEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answer { get; set; }
        public virtual DbSet<Authorizations> Authorizations { get; set; }
        public virtual DbSet<ControlCard> ControlCard { get; set; }
        public virtual DbSet<Detail> Detail { get; set; }
        public virtual DbSet<Pattern> Pattern { get; set; }
        public virtual DbSet<Points> Points { get; set; }
        public virtual DbSet<Sections> Sections { get; set; }
        public virtual DbSet<SPP> SPP { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeUsers> TypeUsers { get; set; }
    }
}
